

###
POST http://localhost:3000/tag
Content-Type: application/json

{
  "name": "标签1"
}

###
GET http://localhost:3000/tag
Accept: application/json

###


POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "分类1"
}

###
GET http://localhost:3000/category
Accept: application/json

###



POST http://localhost:3000/article
Content-Type: application/json

{
  "title": "一个好开头",
  "content": "一段好内容",
  "status": 1,
  "summary": "一个小结",
  "coverURL": "一张好图",
  "category": 1,
  "tags": [
    1
  ]
}

###
GET http://localhost:3000/article
Accept: application/json

###
